### ISSUE TITLE
SQL Injection Vulnerabilities

### ISSUE THREAD

**Issue by jessmphelan** [jessmphelan/PhishingEvaluationGame#11]

**Comment by lauradbryant** [comment]
I've been looking into how to prevent XSS, (No)SQL injections, and CSRF and I think securing our site might be the last thing we do before launching it to the public. Firstly, preventing XSS and NoSQL injections require backend sanitization of user input which it doesn't look like we have set up yet. Secondly these sometimes require adding in middleware or just more code and error handling which at this point will just overcomplicate our code and make it harder to work with since we're still developing it. The best thing we can do right now is make all of the demographic information a dropdown menu so it doesn't take user generated input, but if we're going to let the user make comments on why they thought an email was or wasn't phishing, we're going to have to add in these extra tools anyways.
