### ISSUE TITLE
Verifying our Kaggle LinkedIn Dataset works with IRB Approval

### ISSUE THREAD

**Issue by jessmphelan** [jessmphelan/PhishingEvaluationGame#17]

**Comment by lauradbryant** [comment]
I'm worried about the kaggle data set for two reasons:
1) It's maintained by students at a university in India who claim that it "complies with ethical and legal standards" but there is no way of knowing what ethical standards they're going by and I don't know anything about how their legal standards might compare to ours.
2) The generated emails in GitHub do lead me to identifiable real people. For example, email_2 is to Officer Aaron Zola from someone who works at the Township of Hampton Police Department and if I search Aaron Zola I can easily find his LinkedIn profile that is someone working for the Township of Hampton Police Department. I suppose one could argue that the information that we're using is public, but it still seems to me like we might run into an ethical issue of disclosing information that identifies a real person to all of our participants.

Some ideas for solutions:
1) Depending on how many emails we need we could manually go through and change the name or place of work so that it doesn't lead to a real findable Linkedin profile.
2) We could play around with asking the LLM to at least change the name or maybe even the place of work and other identifiable facts about the person when generating the email.
3) It might be possible to have the LLM create both the Linkedin profile and email. I got fine results just asking it to make me an anonymous profile and giving it a profession (https://chat.openai.com/share/ff7b8dd5-9a58-45e3-a531-63437fd75ca4). It shouldn't be hard to improve this by taking a list of companies and their job postings and another list of universities and asking the model to randomly pick from the list. There's a Kaggle data set (https://www.kaggle.com/datasets/arshkon/linkedin-job-postings) of job postings with their location that someone scraped from linkedin last year, which seems to me like it would have a better chance of being considered ethical because it's no one's personal information and the license says anyone is free to share and modify as long as the creators of the dataset are properly cited.

**Comment by jessmphelan** [comment]
Oh wow, okay then we definitely do not want to use the current dataset that we have. I think your 3rd solution is probably our best bet. Let's plan to implement this instead. I like your idea of taking a list of companies and job postings and another list of universities and then prompting GPT4 to generate LinkedIn profiles randomly from these lists, and then we'll generate our email dataset from there.

**Comment by jessmphelan** [comment]
Something like this for the universities dataset would likely work: https://www.kaggle.com/datasets/anshdwvdi/list-of-all-universities-in-the-world
